# Generated by Django 5.0.3 on 2024-03-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Redirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hits", models.PositiveIntegerField(default=0)),
                ("location", models.CharField(max_length=1023, unique=True)),
                ("user_ip", models.GenericIPAddressField()),
                ("user_agent", models.CharField(blank=True, max_length=1023)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["hits"], name="link_shorte_hits_db49b2_idx")
                ],
            },
        ),
    ]
