# Generated by Django 5.0.3 on 2024-03-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("link_shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirection",
            name="hits",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="redirection",
            name="location",
            field=models.URLField(max_length=1023, unique=True),
        ),
    ]
